export { apiGet, apiPost, apiPut, apiDelete, extractList, isApiConfigured } from './client';
export { normalizeProduct, normalizeCategory, normalizeBrand } from './normalize';
export {
  fetchProducts,
  fetchProductById,
  fetchProductBySlug,
  fetchCategories,
  fetchBrands,
  fetchProductsByCategory,
  fetchProductsByBrand,
  searchProducts,
  fetchFeaturedProducts,
  fetchNewArrivals,
  fetchSaleProducts,
  fetchHomeFeedFromApi,
} from './catalog';
export {
  fetchCart,
  addToCart,
  updateCartItem,
  removeCartItem,
  clearCart,
  fetchWishlist,
  addToWishlist,
  removeFromWishlist,
  fetchOrders,
  fetchOrderById,
  createOrder,
  fetchProfile,
  updateProfile,
  fetchAddresses,
  createAddress,
  updateAddress,
  deleteAddress,
  fetchPaymentMethods,
} from './commerce';
